package main

import (
	"context"
	"errors"
	"net/http"
	"strings"
	"testing"

	"github.com/airiclenz/apogee"
	"github.com/airiclenz/apogee/internal/config"
	"github.com/airiclenz/apogee/internal/domain"
	"github.com/airiclenz/apogee/internal/heartbeat"
	"github.com/airiclenz/apogee/internal/provider"
	"github.com/airiclenz/apogee/internal/title"
)

// namerOn builds a namer over two constant readers with the gate open — the shape every case that
// is not about the gate wires.
func namerOn(session, routed func() (upstreamBinding, provider.EffortDialect, bool)) *delegationNamer {
	sessionOnly := func() (upstreamBinding, provider.EffortDialect) {
		binding, dialect, _ := session()
		return binding, dialect
	}
	return newDelegationNamer(sessionOnly, routed, true)
}

// constUpstream is one fixed reader: the binding and dialect a case pins, always resolved.
func constUpstream(binding upstreamBinding, dialect provider.EffortDialect) func() (upstreamBinding, provider.EffortDialect, bool) {
	return func() (upstreamBinding, provider.EffortDialect, bool) { return binding, dialect, true }
}

// The decision this seam exists for (ADR 0068 decision 2): the naming call goes to the CHILD's own
// Upstream. A routed child's name is generated by the grunt box already warm for that run, and an
// unrouted one's by the session's own server — so a session that sends its delegations somewhere
// cheap does not pay the expensive box one extra completion per spawn.
func TestDelegationNamerBuildsTheCallOnTheChildsUpstream(t *testing.T) {
	t.Parallel()

	sessionSrv, sessionGot := titleServer(t, "read the parser tests")
	targetSrv, targetGot := titleServer(t, "grep the config keys")
	namer := namerOn(
		constUpstream(upstreamBinding{Endpoint: sessionSrv.URL, Model: "smart-70b", APIKey: "sk-session"}, provider.EffortDialectNone),
		constUpstream(upstreamBinding{Endpoint: targetSrv.URL, Model: "cheap-7b", APIKey: "sk-target"}, provider.EffortDialectNone))

	got, err := namer.NameDelegation(context.Background(), domain.DelegationNaming{
		Task: "search the config package for every editable key", Routed: true})
	if err != nil {
		t.Fatalf("NameDelegation for a routed child: %v", err)
	}
	if want := "grep the config keys"; got != want {
		t.Errorf("routed name = %q; want %q — the target server's answer", got, want)
	}
	if targetGot.Model != "cheap-7b" {
		t.Errorf("routed call was addressed to %q; want the target's own model", targetGot.Model)
	}
	if targetGot.Authorization != "Bearer sk-target" {
		t.Errorf("routed call carried %q; want the target's own key", targetGot.Authorization)
	}
	if sessionGot.Model != "" {
		t.Errorf("the session server saw a naming call for a ROUTED child (model %q); want it untouched",
			sessionGot.Model)
	}

	got, err = namer.NameDelegation(context.Background(), domain.DelegationNaming{
		Task: "read every parser test and report the flaky one", Routed: false})
	if err != nil {
		t.Fatalf("NameDelegation for an unrouted child: %v", err)
	}
	if want := "read the parser tests"; got != want {
		t.Errorf("unrouted name = %q; want %q — the session server's answer", got, want)
	}
	if sessionGot.Model != "smart-70b" {
		t.Errorf("unrouted call was addressed to %q; want the session's bound model", sessionGot.Model)
	}

	// The material is the task, and only its excerpt — the instruction rides the system message so
	// a scripted upstream can tell this call apart from every other one the session makes.
	if len(sessionGot.Messages) != 2 {
		t.Fatalf("naming call carried %d messages; want the instruction and the task", len(sessionGot.Messages))
	}
	if role := sessionGot.Messages[0].Role; role != "system" {
		t.Errorf("first message role = %q; want the instruction on the system message", role)
	}
	if !strings.Contains(sessionGot.Messages[0].Content, "2 to 4 lowercase words") {
		t.Errorf("system message = %q; want the delegation instruction", sessionGot.Messages[0].Content)
	}
	if !strings.Contains(sessionGot.Messages[1].Content, "report the flaky one") {
		t.Errorf("user message = %q; want the delegated task", sessionGot.Messages[1].Content)
	}
}

// A routed child whose target has never landed — the beat has not resolved one yet, or this Driver
// has no Sub-agent server at all — is still named: the session's own server answers instead. A name
// from the other box beats no name, which is the degrade every seam in this root takes.
func TestDelegationNamerFallsBackToTheSessionWhenNoTargetLanded(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name   string
		routed func() (upstreamBinding, provider.EffortDialect, bool)
	}{
		{name: "no target has landed", routed: func() (upstreamBinding, provider.EffortDialect, bool) {
			return upstreamBinding{}, provider.EffortDialectNone, false
		}},
		{name: "the Driver has no routing at all", routed: nil},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			srv, got := titleServer(t, "scout the config keys")
			namer := namerOn(
				constUpstream(upstreamBinding{Endpoint: srv.URL, Model: "smart-70b"}, provider.EffortDialectNone),
				tc.routed)

			name, err := namer.NameDelegation(context.Background(),
				domain.DelegationNaming{Task: "scout every config key", Routed: true})
			if err != nil {
				t.Fatalf("NameDelegation: %v", err)
			}
			if want := "scout the config keys"; name != want {
				t.Errorf("name = %q; want %q from the session's own server", name, want)
			}
			if got.Model != "smart-70b" {
				t.Errorf("call was addressed to %q; want the session's bound model", got.Model)
			}
		})
	}
}

// The "answer without thinking" ask has to be SPELLED the way the server that receives it reads
// (ADR 0060), and the server that receives it is the CHILD's — so the dialect travels with the
// binding rather than off the session's latch. A routed child's call therefore states the TARGET's
// dialect even when the session speaks another.
func TestDelegationNamerStatesTheDialectOfTheServerItDials(t *testing.T) {
	t.Parallel()

	reply := titleAttempt{content: "grep the config keys", finishReason: "stop"}
	sessionSrv, sessionBodies := scriptedTitleServer(t, reply)
	targetSrv, targetBodies := scriptedTitleServer(t, reply)
	namer := namerOn(
		constUpstream(upstreamBinding{Endpoint: sessionSrv.URL, Model: "smart-70b"}, provider.EffortDialectKwargs),
		constUpstream(upstreamBinding{Endpoint: targetSrv.URL, Model: "cheap-7b"}, provider.EffortDialectReasoning))

	for _, routed := range []bool{true, false} {
		if _, err := namer.NameDelegation(context.Background(),
			domain.DelegationNaming{Task: "search the config package", Routed: routed}); err != nil {
			t.Fatalf("NameDelegation(routed=%v): %v", routed, err)
		}
	}

	target, session := targetBodies(), sessionBodies()
	if len(target) != 1 || len(session) != 1 {
		t.Fatalf("target saw %d calls and the session %d; want exactly one each", len(target), len(session))
	}
	// OpenRouter's shape on the target, llama.cpp's on the session — each switched OFF, because a
	// two-word name needs no reasoning pass on either box.
	if !strings.Contains(target[0], `"reasoning"`) || !strings.Contains(target[0], `"enabled":false`) {
		t.Errorf("routed body = %s; want the target's reasoning object switched off", target[0])
	}
	if strings.Contains(target[0], "chat_template_kwargs") {
		t.Errorf("routed body = %s; want the SESSION's dialect nowhere on the target's wire", target[0])
	}
	if !strings.Contains(session[0], "chat_template_kwargs") || !strings.Contains(session[0], `"enable_thinking":false`) {
		t.Errorf("unrouted body = %s; want the session's kwargs ask switched off", session[0])
	}
}

// The gate is the live `auto-title:` switch, and it is read at CALL time: with naming off the namer
// answers the empty name the engine drops silently, and — the whole point — makes no request at
// all. A session that switched the key off must stop paying for the completions from the very next
// spawn, not at the next relaunch.
func TestDelegationNamerMakesNoRequestWhileTheGateIsOff(t *testing.T) {
	t.Parallel()

	srv, got := titleServer(t, "scout the config keys")
	session := constUpstream(upstreamBinding{Endpoint: srv.URL, Model: "smart-70b"}, provider.EffortDialectNone)
	sessionOnly := func() (upstreamBinding, provider.EffortDialect) {
		binding, dialect, _ := session()
		return binding, dialect
	}
	namer := newDelegationNamer(sessionOnly, nil, false)

	name, err := namer.NameDelegation(context.Background(), domain.DelegationNaming{Task: "scout every config key"})
	if err != nil {
		t.Fatalf("NameDelegation with the gate shut: %v; want the silent empty answer", err)
	}
	if name != "" {
		t.Errorf("name = %q; want the empty name a shut gate answers", name)
	}
	if got.Model != "" {
		t.Errorf("the server saw a naming call (model %q); want no request made at all", got.Model)
	}

	// And the flip is live in both directions: the very next call goes out.
	namer.setEnabled(true)
	if name, err = namer.NameDelegation(context.Background(),
		domain.DelegationNaming{Task: "scout every config key"}); err != nil {
		t.Fatalf("NameDelegation after the gate opened: %v", err)
	}
	if want := "scout the config keys"; name != want {
		t.Errorf("name = %q; want %q — the flip did not reach the next call", name, want)
	}
}

// The naming call takes the session namer's whole request posture, because it is the same kind of
// call: a stricter server that refuses the thinking kwarg outright gets exactly ONE re-send without
// it, and the retries the Client would otherwise make are off — a cosmetic call must never take a
// single-slot server's queue three times over ahead of the child's own next Turn.
func TestDelegationNamerFallsBackWhenTheThinkingAskIsRejected(t *testing.T) {
	t.Parallel()

	srv, bodies := scriptedTitleServer(t,
		titleAttempt{status: http.StatusBadRequest, errBody: `{"error":"unknown field: chat_template_kwargs"}`},
		titleAttempt{content: "grep the config keys", finishReason: "stop"},
	)
	namer := namerOn(
		constUpstream(upstreamBinding{Endpoint: srv.URL, Model: "smart-70b"}, provider.EffortDialectKwargs), nil)

	got, err := namer.NameDelegation(context.Background(),
		domain.DelegationNaming{Task: "search the config package"})
	if err != nil {
		t.Fatalf("NameDelegation: %v; want the fallback attempt's name", err)
	}
	if want := "grep the config keys"; got != want {
		t.Errorf("name = %q; want %q from the re-send", got, want)
	}
	sent := bodies()
	if len(sent) != 2 {
		t.Fatalf("server saw %d naming POSTs; want the rejected attempt and exactly one fallback", len(sent))
	}
	if strings.Contains(sent[1], "chat_template_kwargs") {
		t.Errorf("fallback body = %s; want the rejected field dropped, not re-sent", sent[1])
	}
}

// A thinking model that ignored the switch burns the whole cap arriving at two words and returns
// finish_reason "length" with nothing in it. That is a REPORTABLE cause rather than the generic
// "nothing usable came back", so it is named — exactly as the session namer names it, off the one
// shared sentinel.
func TestDelegationNamerNamesATruncatedReply(t *testing.T) {
	t.Parallel()

	srv, _ := scriptedTitleServer(t, titleAttempt{content: "  ", finishReason: "length"})
	namer := namerOn(
		constUpstream(upstreamBinding{Endpoint: srv.URL, Model: "smart-70b"}, provider.EffortDialectNone), nil)

	got, err := namer.NameDelegation(context.Background(), domain.DelegationNaming{Task: "search the config package"})
	if !errors.Is(err, title.ErrTruncated) {
		t.Fatalf("NameDelegation = (%q, %v); want title.ErrTruncated", got, err)
	}
}

// The routing wiring's own half of the seam: the dial facts of the target a beat resolves are
// recorded where the push happens, so the host can build a naming call on the Sub-agent server
// without reading them back out of the engine's latch (ADR 0031).
func TestDelegationWiringRecordsTheTargetsBindingForNaming(t *testing.T) {
	t.Parallel()

	entries := []config.ServerEntry{{Name: "grunt", Endpoint: "http://127.0.0.1:2222", Model: "cheap-7b"}}
	wiring, err := newDelegationWiring(
		"grunt", staticServerList(entries), validCfg(t), &delegationSpy{}, noProfiles, nil, config.NewKeyResolver(""))
	if err != nil {
		t.Fatalf("newDelegationWiring: %v", err)
	}

	if _, _, ok := wiring.routedBinding(); ok {
		t.Error("routedBinding reports a target before the first beat landed one")
	}

	wiring.land(wiring.generation, "grunt", &apogee.DelegationTarget{
		Endpoint:      "http://127.0.0.1:2222/v1",
		APIKey:        "sk-grunt",
		Model:         "cheap-7b",
		EffortDialect: provider.EffortDialectReasoning,
	}, nil)

	binding, dialect, ok := wiring.routedBinding()
	if !ok {
		t.Fatal("routedBinding reports no target after a landing; a routed child would be named on the wrong box")
	}
	want := upstreamBinding{Endpoint: "http://127.0.0.1:2222/v1", Model: "cheap-7b", APIKey: "sk-grunt"}
	if binding != want {
		t.Errorf("routedBinding = %+v; want the landed target's own dial facts %+v", binding, want)
	}
	if dialect != provider.EffortDialectReasoning {
		t.Errorf("routedBinding dialect = %q; want the target's own", dialect)
	}

	// A beat that resolves nothing unlatches routing, so nothing spawned after it is routed — and
	// the record stays, because a child ALREADY on the target is still best named there.
	wiring.land(wiring.generation, "grunt", nil, nil)
	if binding, _, ok := wiring.routedBinding(); !ok || binding != want {
		t.Errorf("routedBinding after an unusable beat = (%+v, %v); want the last known target kept", binding, ok)
	}
}

// The composition root installs the namer on the engine's Config — unconditionally, so a session
// that launched with `auto-title: false` can switch naming back on without a relaunch — and wires
// its two readers to the LIVE holders rather than to constants captured at assembly time.
func TestRunRootWiresTheDelegationNamer(t *testing.T) {
	t.Parallel()

	opts := config.Options{
		Endpoint:  "http://127.0.0.1:1111",
		Model:     "model-a",
		Mode:      "ask-before",
		Workspace: t.TempDir(),
		ConfigDir: t.TempDir(),
	}
	roots, err := resolveRoots(opts.ConfigDir, opts.Workspace)
	if err != nil {
		t.Fatalf("resolveRoots: %v", err)
	}
	w := newRootWiring(opts, apogee.ModeAskBefore, roots)
	t.Cleanup(w.close)
	if err := w.resolveConfig(); err != nil {
		t.Fatalf("resolveConfig: %v", err)
	}
	if w.cfg.Namer == nil {
		t.Fatal("Config.Namer is nil; an unnamed delegation would never be named at all")
	}
	if w.cfg.Namer != domain.DelegationNamer(w.namer) {
		t.Error("Config.Namer is not the wiring's namer; the live gate would flip a namer nobody holds")
	}
	if err := w.wireSession(context.Background()); err != nil {
		t.Fatalf("wireSession: %v", err)
	}

	// The session reader is the live holder: a bind moves it, exactly as the session namer's does.
	if binding, _ := w.sessionNamingUpstream(); binding != w.holder.Binding() {
		t.Errorf("sessionNamingUpstream = %+v; want the live holder's %+v", binding, w.holder.Binding())
	}
	w.live.observe(0, provider.EffortDialectReasoning)
	if _, dialect := w.sessionNamingUpstream(); dialect != provider.EffortDialectReasoning {
		t.Errorf("sessionNamingUpstream dialect = %q; want the latch's — the root wired a constant", dialect)
	}

	// And the routed reader is the routing wiring's landing, which this session — naming no
	// Sub-agent server — never has.
	if _, _, ok := w.routedNamingUpstream(); ok {
		t.Error("routedNamingUpstream reports a target for a session that named no Sub-agent server")
	}
}

// The `auto-title:` key is applied LOCALLY by the renderer and never reaches Settings.Apply, so the
// host's namer can only learn about a flip by being told. This is that wire: runRoot hands the
// renderer the hook, and the hook is the namer's own gate.
func TestRunRootWiresTheAutoTitleHookToTheNamer(t *testing.T) {
	t.Parallel()

	opts := config.Options{
		Endpoint:  "http://127.0.0.1:1111",
		Model:     "fake",
		Mode:      "ask-before",
		Workspace: t.TempDir(),
		ConfigDir: t.TempDir(),
		AutoTitle: true,
	}
	roots, err := resolveRoots(opts.ConfigDir, opts.Workspace)
	if err != nil {
		t.Fatalf("resolveRoots: %v", err)
	}
	w := newRootWiring(opts, apogee.ModeAskBefore, roots)
	t.Cleanup(w.close)
	if err := w.resolveConfig(); err != nil {
		t.Fatalf("resolveConfig: %v", err)
	}
	if err := w.wireSession(context.Background()); err != nil {
		t.Fatalf("wireSession: %v", err)
	}
	rendered := w.options()
	if rendered.OnAutoTitle == nil {
		t.Fatal("opts.OnAutoTitle is nil; a /settings flip would leave the delegation namer running")
	}

	srv, got := titleServer(t, "scout the config keys")
	namer := w.namer
	namer.session = func() (upstreamBinding, provider.EffortDialect) {
		return upstreamBinding{Endpoint: srv.URL, Model: "smart-70b"}, provider.EffortDialectNone
	}

	rendered.OnAutoTitle(false)
	if name, err := namer.NameDelegation(context.Background(),
		domain.DelegationNaming{Task: "scout every config key"}); err != nil || name != "" {
		t.Fatalf("NameDelegation after the hook shut the gate = (%q, %v); want the silent empty answer", name, err)
	}
	if got.Model != "" {
		t.Errorf("the server saw a naming call (model %q); want the hook to have shut the gate", got.Model)
	}

	rendered.OnAutoTitle(true)
	if name, err := namer.NameDelegation(context.Background(),
		domain.DelegationNaming{Task: "scout every config key"}); err != nil || name != "scout the config keys" {
		t.Fatalf("NameDelegation after the hook re-opened the gate = (%q, %v); want the generated name", name, err)
	}
}

// Driver parity (ADR 0031): an unattended run names its unnamed delegations too, so a Firing's
// saved record reads like a session's transcript rather than like a wall of task first lines. It
// binds to the run's OWN server — this composition names no `sub-agents-server:`, so nothing is
// routed and there is no other box to ask — and reads the `auto-title:` value the startup resolved,
// an unattended run having no live door to flip it through.
func TestFiringConfigCarriesTheDelegationNamer(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name      string
		autoTitle bool
		wantCall  bool
	}{
		{name: "auto-title on", autoTitle: true, wantCall: true},
		{name: "auto-title off", autoTitle: false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			srv, got := titleServer(t, "scout the config keys")
			entry := config.ServerEntry{Name: "box", Endpoint: srv.URL, Model: "entry-model"}
			cfg, _, _, err := firingConfig(context.Background(), firingInputs{
				opts: config.Options{
					Bypass:    true,
					AutoTitle: tc.autoTitle,
					Servers:   []config.ServerEntry{entry},
				},
				entry:     entry,
				apiKey:    "sk-firing",
				roots:     firingRoots(t),
				manualIDs: nil, // the shipped catalogue is empty (v0.20.0, ADR 0071): no key to spell out
				confiner:  fenceableHost,
				mode:      domain.ModePlan,
				// This Firing's own beat, handed over so the composition spends no round trip on a
				// question this test does not ask: the fixture's server answers naming calls, not
				// discovery.
				beat: func(context.Context, string, string, string) heartbeat.Beat {
					return heartbeat.Beat{Reachable: true, Answered: true}
				},
				recordID: "2026-09-01T09-00-00-firing",
			})
			if err != nil {
				t.Fatalf("firingConfig: %v", err)
			}
			if cfg.Namer == nil {
				t.Fatal("Config.Namer is nil; an unattended run would name none of its delegations")
			}

			// Routed is asked as TRUE deliberately: this Firing resolved no Sub-agent server, so the
			// ask has nowhere else to go and must land on the run's own server rather than nowhere.
			name, err := cfg.Namer.NameDelegation(context.Background(),
				domain.DelegationNaming{Task: "scout every config key", Routed: true})
			if err != nil {
				t.Fatalf("NameDelegation: %v", err)
			}
			if !tc.wantCall {
				if name != "" || got.Model != "" {
					t.Errorf("name = %q and the server saw model %q; want no naming call with the key off",
						name, got.Model)
				}
				return
			}
			if want := "scout the config keys"; name != want {
				t.Errorf("name = %q; want %q", name, want)
			}
			if got.Model != "entry-model" {
				t.Errorf("call was addressed to %q; want the bound entry's model", got.Model)
			}
			if got.Authorization != "Bearer sk-firing" {
				t.Errorf("call carried %q; want the run's own resolved key", got.Authorization)
			}
		})
	}
}

// ADR 0068 decision 2 off the TUI: once an unattended run resolves a Sub-agent server, a ROUTED
// child's naming call goes to that box — the machine already warm for the work answers the question
// about the work — while an unrouted child's still goes to the run's own. Without the routed reader
// every Firing spawn would put a second call on the expensive box, which is the exact cost that
// decision exists to avoid.
func TestFiringConfigNamesARoutedChildOnTheSubAgentServer(t *testing.T) {
	session, sessionCall := titleServer(t, "session name")
	grunt, gruntCall := titleServer(t, "grunt name")

	entry := config.ServerEntry{Name: "box", Endpoint: session.URL, Model: "entry-model"}
	gruntEntry := config.ServerEntry{
		Name:     "grunt",
		Endpoint: grunt.URL,
		Model:    "grunt-model",
		APIKey:   "sk-grunt",
	}

	beats := &stubBeat{beat: heartbeat.Beat{Reachable: true}}
	prev := discoverDelegationBeat
	discoverDelegationBeat = beats.discover
	t.Cleanup(func() { discoverDelegationBeat = prev })

	cfg, routing, _, err := firingConfig(context.Background(), firingInputs{
		opts: config.Options{
			Bypass:          true,
			AutoTitle:       true,
			Servers:         []config.ServerEntry{entry, gruntEntry},
			SubAgentsServer: "grunt",
		},
		entry:     entry,
		apiKey:    "sk-firing",
		roots:     firingRoots(t),
		manualIDs: nil, // the shipped catalogue is empty (v0.20.0, ADR 0071): no key to spell out
		confiner:  fenceableHost,
		mode:      domain.ModePlan,
		// The run's own beat, handed over for the reason above: this fixture's servers answer naming
		// calls, and the Sub-agent server's separate observation is the stub below.
		beat: func(context.Context, string, string, string) heartbeat.Beat {
			return heartbeat.Beat{Reachable: true, Answered: true}
		},
		recordID: "2026-09-02T10-00-00-firing",
	})
	if err != nil {
		t.Fatalf("firingConfig: %v", err)
	}
	if routing.target == nil {
		t.Fatal("the composer resolved no target; the fixture no longer sets up a routed run")
	}

	if _, err := cfg.Namer.NameDelegation(context.Background(),
		domain.DelegationNaming{Task: "grep every config key", Routed: true}); err != nil {
		t.Fatalf("NameDelegation for a routed child: %v", err)
	}
	if gruntCall.Model != "grunt-model" || gruntCall.Authorization != "Bearer sk-grunt" {
		t.Errorf("the routed call reached the Sub-agent server as (%q, %q); want the target's own model and key",
			gruntCall.Model, gruntCall.Authorization)
	}
	if sessionCall.Model != "" {
		t.Errorf("the run's own server saw a routed child's naming call (model %q); want the grunt box to answer "+
			"for its own work (ADR 0068 decision 2)", sessionCall.Model)
	}

	if _, err := cfg.Namer.NameDelegation(context.Background(),
		domain.DelegationNaming{Task: "grep every config key"}); err != nil {
		t.Fatalf("NameDelegation for an unrouted child: %v", err)
	}
	if sessionCall.Model != "entry-model" || sessionCall.Authorization != "Bearer sk-firing" {
		t.Errorf("the unrouted call reached (%q, %q); want the run's own binding",
			sessionCall.Model, sessionCall.Authorization)
	}
}
